### ISSUE TITLE
Problems debugging a project

### ISSUE THREAD

**Issue by mikedavies-dev** [sterin/vscode-xcodebuild-tools#2]
Hi, first of all thanks for this plugin, it is very useful.

I'm having problems getting debugging working though, the project builds fine but if I choose 'Launch Debug Session' the project is built again but nothing happens.

Do I need to create a vscode debug configuration somehow? If so how is that done? I can't see any references to xcode when I try to add a new build configuration for the project.

Thanks!

**Comment by sterin** [comment]
Hi,

Please try version 0.0.6, it should (hopefully) fix the problem. 

The problem was that the `vscode.Debug` was deprecated some time ago. I replaced it with the proper API.

Baruch

**Comment by mikedavies-dev** [comment]
Hey Baruch, thanks for that!

I think I must be missing something though. Nothing appears to have changed after running a debug session. The project builds but nothing runs. This is what I see in the output:

```
[xcodebuild-tools]: Running: xcodebuild -workspace /Users/miked/Projects/project/Builds/MacOSX/ndm.xcworkspace -scheme ndm - App -configuration Debug CONFIGURATION_BUILD_DIR=/Users/user/Projects/project/build/Debug
Build settings from command line:
    CONFIGURATION_BUILD_DIR = /Users/user/Projects/project/build/Debug

=== BUILD TARGET ndm - App OF PROJECT ndm WITH CONFIGURATION Debug ===

Check dependencies

** BUILD SUCCEEDED **

[xcodebuild-tools]: exited normally.
```

Do I need to configure something in `launch.json`?

**Comment by sterin** [comment]
I added a working example with debugging a few hours ago. Please take a look at https://github.com/sterin/vscode-xcodebuild-tools/blob/797438a45a504dcc88410ad7300d1d6432202a64/example/helloworld/.vscode/xcodebuild-tools.json#L24-L33
You can have multiple entries there (with different programs, arguments, working directories and names). 

You just need to select the debug configuration you'd like to use and execute the 'Launch Debug Session' or 'Run without Debugging' commands. It will automatically start a debug session as if existed in `launch.json`.

**Comment by mikedavies-dev** [comment]
Fantastic! I'm still not sure exactly what was wrong before but it's working perfectly now!

Btw, I had to add the path into my .app:
`${buildPath}/ndm.app/Contents/MacOS/ndm`

I'm still fairly new to MacOS development so maybe thats obvious to experienced developers but maybe worth mentioning.

Thanks again for the help!
